#!/bin/sh
if [ "`git branch | grep \* | cut -f2 -d' '`" == "master" ]
then

mysqldump -u dbuser -pdbpass --routines halaya > SQLVersionControl/halaya_dev.full.sql
mysqldump -u dbuser -pdbpass --routines --no-data=true halaya > SQLVersionControl/halaya_dev.structure.sql
mysqldump -u dbuser -pdbpass --no-create-info --compact --extended-insert=false halaya > SQLVersionControl/halaya_dev.data.sql

git add SQLVersionControl/halaya_dev.full.sql
git add SQLVersionControl/halaya_dev.structure.sql
git add SQLVersionControl/halaya_dev.data.sql

elif [ "`git branch | grep \* | cut -f2 -d' '`" == "gbiz" ]
then

mysqldump -u dbuser -pdbpass --routines gbiz > SQLVersionControl/gbiz_dev.full.sql
mysqldump -u dbuser -pdbpass --routines --no-data=true gbiz > SQLVersionControl/gbiz_dev.structure.sql
mysqldump -u dbuser -pdbpass --no-create-info --compact --extended-insert=false gbiz > SQLVersionControl/gbiz_dev.data.sql

git add SQLVersionControl/gbiz_dev.full.sql
git add SQLVersionControl/gbiz_dev.structure.sql
git add SQLVersionControl/gbiz_dev.data.sql

elif [ "`git branch | grep \* | cut -f2 -d' '`" == "cmlsl" ]
then

mysqldump -u dbuser -pdbpass --routines cmlsl > SQLVersionControl/cmlsl_dev.full.sql
mysqldump -u dbuser -pdbpass --routines --no-data=true cmlsl > SQLVersionControl/cmlsl_dev.structure.sql
mysqldump -u dbuser -pdbpass --no-create-info --compact --extended-insert=false cmlsl > SQLVersionControl/cmlsl_dev.data.sql

git add SQLVersionControl/cmlsl_dev.full.sql
git add SQLVersionControl/cmlsl_dev.structure.sql
git add SQLVersionControl/cmlsl_dev.data.sql

elif [ "`git branch | grep \* | cut -f2 -d' '`" == "soulmap" ]
then

mysqldump -u dbuser -pdbpass --routines soulmap > SQLVersionControl/soulmap_dev.full.sql
mysqldump -u dbuser -pdbpass --routines --no-data=true soulmap > SQLVersionControl/soulmap_dev.structure.sql
mysqldump -u dbuser -pdbpass --no-create-info --compact --extended-insert=false soulmap > SQLVersionControl/soulmap_dev.data.sql

git add SQLVersionControl/soulmap_dev.full.sql
git add SQLVersionControl/soulmap_dev.structure.sql
git add SQLVersionControl/soulmap_dev.data.sql

fi
exit 0
