#!/bin/sh

mysqldump -u dbuser -pdbpass --routines hndshkif > /zipstore/www/hndshkif/SQLVersionControl/hndshkif_dev.full.sql
mysqldump -u dbuser -pdbpass --routines --no-data=true hndshkif > /zipstore/www/hndshkif/SQLVersionControl/hndshkif_dev.structure.sql
mysqldump -u dbuser -pdbpass --no-create-info --compact --extended-insert=false hndshkif > /zipstore/www/hndshkif/SQLVersionControl/hndshkif_dev.data.sql

NOW=$(date +"%Y%m%d%H%M%S")
FULL="hndshkif_dev.full.$NOW.sql"
STRUCTURE="hndshkif_dev.structure.$NOW.sql"
DATA="hndshkif_dev.data.$NOW.sql"

cp /zipstore/www/hndshkif/SQLVersionControl/hndshkif_dev.full.sql /zipstore/docs/dunstan.nesbit@gmail.com/Work/Shazam/SQLVersionControl/$FULL
cp /zipstore/www/hndshkif/SQLVersionControl/hndshkif_dev.structure.sql /zipstore/docs/dunstan.nesbit@gmail.com/Work/Shazam/SQLVersionControl/$STRUCTURE
cp /zipstore/www/hndshkif/SQLVersionControl/hndshkif_dev.data.sql /zipstore/docs/dunstan.nesbit@gmail.com/Work/Shazam/SQLVersionControl/$DATA

#git add SQLVersionControl/halaya_dev.full.sql
#git add SQLVersionControl/halaya_dev.structure.sql
#git add SQLVersionControl/halaya_dev.data.sql
