#!/bin/sh

APPNAME=hndshkif
ENV=DEV
SERVER=localhost
APPURLBASE="http://${SERVER}/${APPNAME}"
DBNAME=hndshkif
DBUSER=dbuser
DBPASS=dbpass
APPRO0T="/zipstore/www/${APPNAME}/"
DATADUMPDIR="${APPRO0T}SQLVersionControl/"
BACKUPDIR="/zipstore/docs/dunstan.nesbit@gmail.com/sql/${DBNAME}/"
NOW=$(date +"%Y%m%d-%H%M%S")
BACKUPCOPY=1
DEBUG=1

DB_FULL_FILE="${NOW}_${ENV}_${DBNAME}_full.sql"
DB_STRUCTURE_FILE="${NOW}_${ENV}_${DBNAME}_structure.sql"
DB_DATA_FILE="${NOW}_${ENV}_${DBNAME}_data.sql"

#### change to application root directory
cd "$APPROOT"

#### get last git commit id
GIT_COMMIT=$(git log --format='%H' -n 1)
URL="${APPURLBASE}/index.php/core_ajaxtodb?option=versionupdate&appver=${GIT_COMMIT}&dbver=${NOW}&env=${ENV}"
if [ "$DEBUG" -eq 1 ]; then
echo "VERSION UPDATE    : ${URL}"
fi
curl ${URL}

#### dump database
if [ "$DEBUG" -eq 1 ]; then
echo "DB_FULL_FILE      : ${DB_FULL_FILE}"
echo "DB_STRUCTURE_FILE : ${DB_STRUCTURE_FILE}"
echo "DB_DATA_FILE      : ${DB_DATA_FILE}"
fi
mysqldump -u ${DBUSER} -p${DBPASS} --routines ${DBNAME} > ${DATADUMPDIR}${DB_FULL_FILE}
mysqldump -u ${DBUSER} -p${DBPASS} --routines --no-data=true ${DBNAME} > ${DATADUMPDIR}${DB_STRUCTURE_FILE}
mysqldump -u ${DBUSER} -p${DBPASS} --no-create-info --compact --extended-insert=false ${DBNAME} > ${DATADUMPDIR}${DB_DATA_FILE}

#### copy datadumps to backup directory
if [ "$BACKUPCOPY" -eq 1 ]; then
cp ${DATADUMPDIR}${DB_FULL_FILE} ${BACKUPDIR}${DB_FULL_FILE}
cp ${DATADUMPDIR}${DB_STRUCTURE_FILE} ${BACKUPDIR}${DB_STRUCTURE_FILE}
cp ${DATADUMPDIR}${DB_DATA_FILE} ${BACKUPDIR}${DB_DATA_FILE}
fi
exit 0